2022-01-04 01:36:53:3653 error: "error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\pg-protocol\\src\\parser.ts:188:21)\n    at Parser.parse (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\pg-protocol\\src\\parser.ts:103:30)\n    at Socket.<anonymous> (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:390:28)\n    at Socket.emit (node:domain:475:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)"
2022-01-04 01:37:45:3745 error: "error: database \"test2\" does not exist\n    at Parser.parseErrorMessage (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\pg-protocol\\src\\parser.ts:188:21)\n    at Parser.parse (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\pg-protocol\\src\\parser.ts:103:30)\n    at Socket.<anonymous> (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:390:28)\n    at Socket.emit (node:domain:475:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)"
2022-01-04 01:40:48:4048 error: "error: database \"test\" does not exist\n    at Parser.parseErrorMessage (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\pg-protocol\\src\\parser.ts:188:21)\n    at Parser.parse (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\pg-protocol\\src\\parser.ts:103:30)\n    at Socket.<anonymous> (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:390:28)\n    at Socket.emit (node:domain:475:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)"
2022-01-10 00:11:42:1142 error: "error: password authentication failed for user \"postgres\"\n    at Parser.parseErrorMessage (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\pg-protocol\\src\\parser.ts:369:69)\n    at Parser.handlePacket (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\pg-protocol\\src\\parser.ts:188:21)\n    at Parser.parse (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\pg-protocol\\src\\parser.ts:103:30)\n    at Socket.<anonymous> (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:390:28)\n    at Socket.emit (node:domain:475:12)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)"
2022-01-16 14:27:03:273 error: {"method":"GET","params":{},"url":"/users","query":{},"body":"Internal Server Error","responseCode":500,"stack":"QueryFailedError: relation \"users\" does not exist\n    at QueryFailedError.TypeORMError [as constructor] (E:\\work\\test\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\work\\test\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\work\\test\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\work\\test\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
